// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtCtxk0_MXHSI4oTVMJC_IIB1OXVRAfLs',
    appId: '1:473264691621:web:f6cb86a04b27d72a0eb04c',
    messagingSenderId: '473264691621',
    projectId: 'lumina-26e6b',
    authDomain: 'lumina-26e6b.firebaseapp.com',
    databaseURL: 'https://lumina-26e6b-default-rtdb.firebaseio.com',
    storageBucket: 'lumina-26e6b.appspot.com',
    measurementId: 'G-H6ER4QXFRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgeo9i1bnfC1d1iB2r3R_YKHEWHL_-KZc',
    appId: '1:473264691621:android:969baebf9a6e8d3f0eb04c',
    messagingSenderId: '473264691621',
    projectId: 'lumina-26e6b',
    databaseURL: 'https://lumina-26e6b-default-rtdb.firebaseio.com',
    storageBucket: 'lumina-26e6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD053vgJb2sJX0oPTk6ktaRtSsGrBHpg4I',
    appId: '1:473264691621:ios:4ca0829f9e58eaf30eb04c',
    messagingSenderId: '473264691621',
    projectId: 'lumina-26e6b',
    databaseURL: 'https://lumina-26e6b-default-rtdb.firebaseio.com',
    storageBucket: 'lumina-26e6b.appspot.com',
    iosBundleId: 'com.gytx.lumina',
  );
}
